# Generated by Django 3.2.7 on 2021-09-18 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=500)),
                ('news_categort', models.CharField(max_length=50)),
                ('news_subcategory', models.CharField(max_length=50)),
                ('news_summery', models.CharField(max_length=500)),
                ('news_author', models.CharField(max_length=50)),
                ('news_updateTime', models.DateTimeField(default=datetime.datetime(2021, 9, 18, 20, 24, 43, 466579))),
                ('news_image', models.ImageField(upload_to='./static/images')),
                ('news_place', models.CharField(max_length=20)),
                ('news_paragraph', models.TextField()),
            ],
        ),
    ]
