# Generated by Django 3.2.4 on 2021-09-20 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20210918_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaking', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='news_updateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 11, 19, 34, 979138)),
        ),
    ]
