# Generated by Django 3.2.7 on 2021-09-20 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_auto_20210920_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='news_updateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 17, 40, 26, 770782)),
        ),
    ]
