# Generated by Django 3.2.7 on 2021-09-21 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_alter_new_news_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='news_updateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 8, 8, 56, 332670)),
        ),
    ]
